#!/bin/bash
# ONNX Runtime Installation Script for jetson_nano
# Generated by CiRA Pipeline Builder

set -e  # Exit on error

echo "======================================"
echo "CiRA Dependencies Setup"
echo "Platform: jetson_nano"
echo "======================================"
echo ""

# ONNX Runtime configuration
ONNX_VERSION="1.12.0"
ARCH="aarch64"
ONNX_PACKAGE="onnxruntime-linux-${ARCH}-${ONNX_VERSION}"
DOWNLOAD_URL="https://github.com/microsoft/onnxruntime/releases/download/v${ONNX_VERSION}/${ONNX_PACKAGE}.tgz"

echo "Checking for existing ONNX Runtime installation..."
if [ -f "/usr/local/lib/libonnxruntime.so" ]; then
    echo "ONNX Runtime already installed at /usr/local"
    echo "If you want to reinstall, run: sudo rm -rf /usr/local/include/onnxruntime* /usr/local/lib/libonnxruntime*"
    exit 0
fi

echo "Downloading ONNX Runtime ${ONNX_VERSION} for ${ARCH}..."
wget -q --show-progress "${DOWNLOAD_URL}" -O /tmp/${ONNX_PACKAGE}.tgz

echo "Extracting ONNX Runtime..."
tar -xzf /tmp/${ONNX_PACKAGE}.tgz -C /tmp/

echo "Installing ONNX Runtime to /usr/local..."
sudo cp -r /tmp/${ONNX_PACKAGE}/include/* /usr/local/include/
sudo cp -r /tmp/${ONNX_PACKAGE}/lib/* /usr/local/lib/

echo "Updating library cache..."
sudo ldconfig

echo "Cleaning up..."
rm -rf /tmp/${ONNX_PACKAGE}*

echo ""
echo "======================================"
echo "Installation Complete!"
echo "======================================"
echo ""
echo "ONNX Runtime has been installed to /usr/local"
echo "You can now build the project with:"
echo "  mkdir build && cd build"
echo "  cmake .."
echo "  make"
echo ""

exit 0
